name: Run Unit Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pester-test:
    name: Test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      # - name: Setup PowerShell module cache
      #   id: cacher
      #   uses: actions/cache@v3
      #   with:
      #     path: "~/.local/share/powershell/Modules"
      #     key: ${{ runner.os }}-SecretManagement
      # - name: Install from PSGallery
      #   shell: pwsh
      #   run: |
      #     Set-PSRepository PSGallery -InstallationPolicy Trusted
      #     Install-Module Microsoft.Powershell.SecretManagement
      - name: Run Tests
        shell: pwsh
        run: |
          # $InformationPreference = "Continue"
          ./run-tests.ps1
